// AUTO-GENERATED - do not edit. Generated by generate-entity-types.js
// eslint-disable

export interface ChangePasswordDto {
  email: string;
  newPassword: string;
}

export interface VerifyForgotPasswordDto {
  email: string;
  otp: string;
}

export interface ForgotPasswordDto {
  email: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface VerifyRegistrationDto {
  otp?: string;
}

export interface CreateLevelDto {
  name: string;
  order: number;
  description?: string;
}

export interface RemoveLevelDto {
  order: number;
}

export interface UpdateLevelDto {
  name?: string;
  order?: number;
  description?: string;
}

export interface Level {
  name: string;
  order: number;
  description?: string;
  _id: string;
  createdAt: string;
  updatedAt: string;
  sections: Section[];
}

export interface CreateSectionDto {
  name: string;
  order: number;
  description?: string;
  level: string;
  videoId: string;
}

export interface RemoveSectionDto {
  order: number;
}

export interface UpdateSectionDto {
  name?: string;
  order?: number;
  description?: string;
  level?: string;
  videoId?: string;
}

export interface Section {
  name: string;
  order: number;
  description: string;
  videoId: string;
  level: Level;
  _id: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserDto {
  email: string;
  name: string;
  age: number;
  gender: string;
  phonenumber: string;
  role: string;
  password: string;
}

export interface UpdateUserDto {
  email?: string;
  name?: string;
  age?: number;
  gender?: string;
  phonenumber?: string;
  role?: string;
  password?: string;
  completedSections?: string[];
  completedLevels?: string[];
}

export interface User {
  email: string;
  name: string;
  age: number;
  gender: "male" | "female";
  role: "admin" | "user";
  phonenumber: string;
  password: string;
  completedLevels: Level[];
  completedSections: Section[];
  _id: string;
  createdAt: string;
  updatedAt: string;
}
